name: EOL Dependencies Check
on:
  schedule:
    - cron: '0 11 * * 1'  # Weekly on Mondays at 11:00 UTC
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  eol_dependency_check:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-eol-analysis.yml@main

